version: '3.8'

services:
  auth-service:
    image: bamlakhiruy/auth-service:latest
    ports:
      - "3001:3000"
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s

  transaction-service:
    image: bamlakhiruy/transaction-service:latest
    ports:
      - "3002:3000"
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s

  user-service:
    image: bamlakhiruy/user-service:latest
    ports:
      - "3003:3000"
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
