version: '3.8'

services:
  auth-service:
    image: auth-service:latest
    build: ./auth-service
    ports:
      - "3001:3000"
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s

  transaction-service:
    image: transaction-service:latest
    build: ./transaction-service
    ports:
      - "3002:3000"
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s

  user-service:
    image: user-service:latest
    build: ./user-service
    ports:
      - "3003:3000"
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s

